---
# This playbook deploys the whole application stack in this site.

- name: Cloning QEMU VMs using Virt-Clone
  hosts: all
  remote_user: mdigiacomi
  become_method: sudo
  become_user: root

  roles:
    - vm
