---

- name: Viewing List of Current Domains
  command: bash -c "virsh list --all"
  become: true
- name: Cloning VM {{New_VM_Name}} from {{Source_VM_Name}}
  command: bash -c "virt-clone --original {{Source_VM_Name}} --name {{New_VM_Name}} --auto-clone"
  become: true
- name:    Starting VM
  command: bash -c "virsh start {{New_VM_Name}}"
  become: true